#!/usr/bin/env python3
"""
Master Session Prep - AI Powered Daily Research
Runs before each session to prepare levels, news, and context
Uses Ollama local AI (no API costs)
"""

import requests
import json
import os
from datetime import datetime

OLLAMA_URL = "http://localhost:11434/api/generate"
WATCHLIST_DIR = "/tmp/trading-desk/data/watchlists"
OUTPUT_DIR = "/tmp/trading-desk/session_prep"
SESSION_TIMES = {
    "asian": {"hour": 0, "name": "ASIAN", "utc": "00:00"},
    "london": {"hour": 7, "name": "LONDON", "utc": "07:00"},  
    "ny": {"hour": 12, "name": "NEW YORK", "utc": "12:00"}
}

def get_current_session():
    """Determine current session based on UTC hour"""
    now = datetime.utcnow()
    utc_hour = now.hour
    
    if utc_hour < 7:
        return "asian"
    elif utc_hour < 12:
        return "london"
    else:
        return "ny"

def load_watchlist(session: str) -> list:
    """Load session watchlist"""
    path = f"{WATCHLIST_DIR}/{session}_session.txt"
    if not os.path.exists(path):
        return []
    with open(path) as f:
        return [l.strip() for l in f if l.strip() and not l.startswith('#')]

def load_keywords() -> list:
    """Load trading keywords"""
    path = f"{WATCHLIST_DIR}/keywords.txt"
    if not os.path.exists(path):
        return []
    with open(path) as f:
        return [l.strip() for l in f if l.strip() and not l.startswith('#')]

def call_ollama(prompt: str, model: str = "qwen2.5-coder:7b", timeout: int = 120) -> str:
    """Call Ollama for AI inference"""
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False
    }
    try:
        response = requests.post(OLLAMA_URL, json=payload, timeout=timeout)
        result = response.json()
        return result.get("response", "Error: No response")
    except Exception as e:
        return f"Error: {str(e)}"

def generate_session_brief(session: str, instruments: list, keywords: list) -> str:
    """Generate AI-powered session brief"""
    
    prompt = f"""You are a trading research assistant preparing for {session.upper()} session.

DATE: {datetime.now().strftime('%Y-%m-%d')}
SESSION: {session.upper()}

YOUR INSTRUMENTS:
{', '.join(instruments)}

TRADING KEYWORDS TO WATCH:
{', '.join(keywords)}

Generate a concise pre-session brief with these sections:

## {session.upper()} SESSION BRIEF - {datetime.now().strftime('%Y-%m-%d')}

### 1. KEY LEVELS TO WATCH
For your main instruments, identify key daily/weekly levels based on recent price action.

### 2. SESSION CHARACTERISTICS
Is this typically a high/low volatility session for your instruments?
What timeframes are most relevant?

### 3. CATALYSTS TODAY
Any scheduled economic events, central bank speakers, or market-moving data.

### 4. INSTITUTIONAL FLOW THEMES
What might institutions be doing based on current market conditions?

### 5. TRADE SETUP IDEAS
2-3 potential high-probability setups for this session based on ICT methodology.

Keep it actionable and under 400 words. Focus on orderflow and session pathology."""

    return call_ollama(prompt)

def generate_market_context() -> str:
    """Generate overall market context"""
    
    prompt = """Provide a Brief market context for trading forex and futures:

1. Current risk sentiment (risk-on/risk-off)
2. Dollar strength/weakness bias
3. Key macro themes of the week
4. Any notable market structures or anomalies

Be concise - 3-4 bullet points max."""

    return call_ollama(prompt)

def run_session_prep():
    """Run full session prep"""
    session = get_current_session()
    session_info = SESSION_TIMES.get(session, SESSION_TIMES["london"])
    instruments = load_watchlist(session)
    keywords = load_keywords()
    
    print(f"Running {session.upper()} session prep...")
    print(f"Session UTC: {session_info['utc']}")
    print(f"Watchlist: {len(instruments)} instruments")
    
    # Generate briefs
    print("\nGenerating session brief...")
    brief = generate_session_brief(session, instruments, keywords)
    
    print("\nGenerating market context...")
    context = generate_market_context()
    
    # Combine output
    output = f"""
{'='*60}
{session_info['name']} SESSION PREP
{datetime.now().strftime('%Y-%m-%d %H:%M UTC')}
{'='*60}

## MARKET CONTEXT
{context}

{'='*60}

## SESSION BRIEF
{brief}

{'='*60}
INSTRUMENTS: {', '.join(instruments)}
KEYWORDS: {', '.join(keywords[:10])}...
Generated by Trading Desk AI (Ollama + Qwen2.5-Coder)
"""
    
    # Save to file
    date_str = datetime.now().strftime('%Y-%m-%d')
    output_path = f"{OUTPUT_DIR}/{date_str}_{session}_brief.md"
    with open(output_path, 'w') as f:
        f.write(output)
    
    print(f"\nSaved to: {output_path}")
    print(output)
    
    return output

if __name__ == "__main__":
    run_session_prep()
