#!/usr/bin/env python3
"""Trading News Desk"""

import requests
import xml.etree.ElementTree as ET
import os
import json
from datetime import datetime

OLLAMA_URL = "http://localhost:11434/api/generate"
WATCHLIST_DIR = "/tmp/trading-desk/data/watchlists"
NEWS_DIR = "/tmp/trading-desk/news_desk"

FEEDS = {
    "ForexLive": "https://www.forexlive.com/feed/news",
    "Investing.com": "https://www.investing.com/rss/news.rss", 
}

def parse_rss(url):
    try:
        resp = requests.get(url, timeout=15)
        if resp.status_code != 200:
            return []
        root = ET.fromstring(resp.content)
        items = []
        for item in root.findall(".//item")[:10]:
            items.append({
                "title": item.findtext("title", ""),
                "link": item.findtext("link", ""),
                "pubDate": item.findtext("pubDate", ""),
                "description": (item.findtext("description") or "")[:200]
            })
        return items
    except:
        return []

def load_instruments():
    instruments = set()
    for session in ["asian", "london", "ny"]:
        path = os.path.join(WATCHLIST_DIR, session + "_session.txt")
        if os.path.exists(path):
            with open(path) as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#"):
                        instruments.add(line.split()[0])
    return instruments

def fetch_all_news():
    all_articles = []
    seen = set()
    for source, url in FEEDS.items():
        for article in parse_rss(url):
            if article["title"] not in seen:
                seen.add(article["title"])
                article["source"] = source
                all_articles.append(article)
    return all_articles

def filter_relevant(articles, instruments):
    relevant = []
    for article in articles:
        title = article.get("title", "").upper()
        matched = []
        for inst in instruments:
            if inst.upper() in title:
                matched.append(inst)
        if matched:
            article["matched"] = matched
            relevant.append(article)
    return relevant

def analyze_impact(article):
    prompt = '''Analyze this news headline for trading impact. Reply with JSON only:
{"impact": "HIGH/MEDIUM/LOW", "direction": "BULLISH/BEARISH/NEUTRAL", "instruments": ["list"]}

Headline: ''' + article["title"]
    try:
        resp = requests.post(OLLAMA_URL, json={
            "model": "qwen2.5-coder:7b",
            "prompt": prompt,
            "stream": False,
            "format": "json"
        }, timeout=60)
        return json.loads(resp.json().get("response", "{}"))
    except:
        return {"impact": "LOW", "direction": "NEUTRAL", "instruments": []}

def generate_brief(session="london"):
    instruments = load_instruments()
    articles = fetch_all_news()
    relevant = filter_relevant(articles, instruments)
    
    if not relevant:
        return "No relevant news found."
    
    analyzed = []
    for article in relevant[:5]:
        article["analysis"] = analyze_impact(article)
        analyzed.append(article)
    
    output_lines = [
        "# TRADING NEWS BRIEF",
        datetime.now().strftime("%Y-%m-%d %H:%M UTC") + " | Session: " + session.upper(),
        "",
        "## TOP NEWS",
        ""
    ]
    
    for a in analyzed:
        impact = a["analysis"].get("impact", "?")
        emoji = "[HIGH]" if impact == "HIGH" else "[MED]" if impact == "MEDIUM" else "[LOW]"
        output_lines.append("### " + emoji + " " + a["title"][:80])
        output_lines.append("Impact: " + impact + " | Direction: " + a["analysis"].get("direction", "?"))
        matched = a["analysis"].get("instruments", a.get("matched", []))
        output_lines.append("Instruments: " + ", ".join(matched))
        output_lines.append("")
    
    output_lines.append("Generated by Trading Desk AI")
    
    output = "\n".join(output_lines) + "\n"
    
    os.makedirs(NEWS_DIR, exist_ok=True)
    path = os.path.join(NEWS_DIR, datetime.now().strftime("%Y-%m-%d") + "_" + session + "_news.md")
    with open(path, "w") as f:
        f.write(output)
    
    return output

if __name__ == "__main__":
    print(generate_brief())
